// Comprehensive NSE Stock Data - 500+ Stocks
const nseStocksData = [
    // Nifty 50 Stocks
    { symbol: 'RELIANCE', name: 'Reliance Industries', basePrice: 2450.50, sector: 'Energy' },
    { symbol: 'TCS', name: 'Tata Consultancy Services', basePrice: 3680.75, sector: 'IT' },
    { symbol: 'HDFCBANK', name: 'HDFC Bank', basePrice: 1650.25, sector: 'Banking' },
    { symbol: 'INFY', name: 'Infosys', basePrice: 1520.80, sector: 'IT' },
    { symbol: 'ICICIBANK', name: 'ICICI Bank', basePrice: 985.40, sector: 'Banking' },
    { symbol: 'HINDUNILVR', name: 'Hindustan Unilever', basePrice: 2380.60, sector: 'FMCG' },
    { symbol: 'ITC', name: 'ITC Limited', basePrice: 425.30, sector: 'FMCG' },
    { symbol: 'SBIN', name: 'State Bank of India', basePrice: 625.75, sector: 'Banking' },
    { symbol: 'BHARTIARTL', name: 'Bharti Airtel', basePrice: 1180.90, sector: 'Telecom' },
    { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank', basePrice: 1785.50, sector: 'Banking' },
    { symbol: 'LT', name: 'Larsen & Toubro', basePrice: 3420.25, sector: 'Infrastructure' },
    { symbol: 'ASIANPAINT', name: 'Asian Paints', basePrice: 2950.80, sector: 'Paints' },
    { symbol: 'MARUTI', name: 'Maruti Suzuki', basePrice: 10250.40, sector: 'Auto' },
    { symbol: 'TITAN', name: 'Titan Company', basePrice: 3180.60, sector: 'Jewelry' },
    { symbol: 'WIPRO', name: 'Wipro', basePrice: 445.75, sector: 'IT' },
    { symbol: 'AXISBANK', name: 'Axis Bank', basePrice: 1085.30, sector: 'Banking' },
    { symbol: 'HCLTECH', name: 'HCL Technologies', basePrice: 1450.20, sector: 'IT' },
    { symbol: 'BAJFINANCE', name: 'Bajaj Finance', basePrice: 6850.40, sector: 'Finance' },
    { symbol: 'ULTRACEMCO', name: 'UltraTech Cement', basePrice: 9250.75, sector: 'Cement' },
    { symbol: 'SUNPHARMA', name: 'Sun Pharmaceutical', basePrice: 1485.60, sector: 'Pharma' },
    { symbol: 'NESTLEIND', name: 'Nestle India', basePrice: 24500.80, sector: 'FMCG' },
    { symbol: 'TATAMOTORS', name: 'Tata Motors', basePrice: 785.40, sector: 'Auto' },
    { symbol: 'TECHM', name: 'Tech Mahindra', basePrice: 1285.90, sector: 'IT' },
    { symbol: 'ONGC', name: 'Oil & Natural Gas Corp', basePrice: 245.60, sector: 'Energy' },
    { symbol: 'NTPC', name: 'NTPC Limited', basePrice: 325.80, sector: 'Power' },
    { symbol: 'POWERGRID', name: 'Power Grid Corp', basePrice: 285.40, sector: 'Power' },
    { symbol: 'M&M', name: 'Mahindra & Mahindra', basePrice: 1850.75, sector: 'Auto' },
    { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv', basePrice: 1685.30, sector: 'Finance' },
    { symbol: 'ADANIENT', name: 'Adani Enterprises', basePrice: 2850.60, sector: 'Diversified' },
    { symbol: 'TATASTEEL', name: 'Tata Steel', basePrice: 145.80, sector: 'Steel' },
    { symbol: 'COALINDIA', name: 'Coal India', basePrice: 425.40, sector: 'Mining' },
    { symbol: 'JSWSTEEL', name: 'JSW Steel', basePrice: 885.60, sector: 'Steel' },
    { symbol: 'HINDALCO', name: 'Hindalco Industries', basePrice: 625.30, sector: 'Metals' },
    { symbol: 'INDUSINDBK', name: 'IndusInd Bank', basePrice: 1425.80, sector: 'Banking' },
    { symbol: 'ADANIPORTS', name: 'Adani Ports', basePrice: 1285.40, sector: 'Infrastructure' },
    { symbol: 'DIVISLAB', name: 'Divi\'s Laboratories', basePrice: 3650.75, sector: 'Pharma' },
    { symbol: 'DRREDDY', name: 'Dr. Reddy\'s Labs', basePrice: 5850.60, sector: 'Pharma' },
    { symbol: 'CIPLA', name: 'Cipla', basePrice: 1385.40, sector: 'Pharma' },
    { symbol: 'EICHERMOT', name: 'Eicher Motors', basePrice: 4250.80, sector: 'Auto' },
    { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp', basePrice: 4685.30, sector: 'Auto' },
    { symbol: 'GRASIM', name: 'Grasim Industries', basePrice: 2185.60, sector: 'Diversified' },
    { symbol: 'BRITANNIA', name: 'Britannia Industries', basePrice: 4850.75, sector: 'FMCG' },
    { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals', basePrice: 5650.40, sector: 'Healthcare' },
    { symbol: 'BPCL', name: 'Bharat Petroleum', basePrice: 585.80, sector: 'Energy' },
    { symbol: 'TATACONSUM', name: 'Tata Consumer Products', basePrice: 1085.30, sector: 'FMCG' },
    { symbol: 'SHRIRAMFIN', name: 'Shriram Finance', basePrice: 2450.60, sector: 'Finance' },
    { symbol: 'SBILIFE', name: 'SBI Life Insurance', basePrice: 1485.75, sector: 'Insurance' },
    { symbol: 'HDFCLIFE', name: 'HDFC Life Insurance', basePrice: 685.40, sector: 'Insurance' },
    { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto', basePrice: 9250.80, sector: 'Auto' },
    { symbol: 'LTIM', name: 'LTIMindtree', basePrice: 5850.30, sector: 'IT' },

    // Banking & Finance
    { symbol: 'BANKBARODA', name: 'Bank of Baroda', basePrice: 235.60, sector: 'Banking' },
    { symbol: 'PNB', name: 'Punjab National Bank', basePrice: 105.40, sector: 'Banking' },
    { symbol: 'CANBK', name: 'Canara Bank', basePrice: 115.80, sector: 'Banking' },
    { symbol: 'UNIONBANK', name: 'Union Bank of India', basePrice: 125.30, sector: 'Banking' },
    { symbol: 'IDFCFIRSTB', name: 'IDFC First Bank', basePrice: 85.60, sector: 'Banking' },
    { symbol: 'FEDERALBNK', name: 'Federal Bank', basePrice: 165.40, sector: 'Banking' },
    { symbol: 'BANDHANBNK', name: 'Bandhan Bank', basePrice: 225.80, sector: 'Banking' },
    { symbol: 'AUBANK', name: 'AU Small Finance Bank', basePrice: 685.30, sector: 'Banking' },
    { symbol: 'RBLBANK', name: 'RBL Bank', basePrice: 245.60, sector: 'Banking' },
    { symbol: 'YESBANK', name: 'Yes Bank', basePrice: 22.40, sector: 'Banking' },
    { symbol: 'CHOLAFIN', name: 'Cholamandalam Investment', basePrice: 1285.75, sector: 'Finance' },
    { symbol: 'MUTHOOTFIN', name: 'Muthoot Finance', basePrice: 1685.40, sector: 'Finance' },
    { symbol: 'LICHSGFIN', name: 'LIC Housing Finance', basePrice: 585.60, sector: 'Finance' },
    { symbol: 'PFC', name: 'Power Finance Corp', basePrice: 425.80, sector: 'Finance' },
    { symbol: 'RECLTD', name: 'REC Limited', basePrice: 485.30, sector: 'Finance' },
    { symbol: 'ICICIGI', name: 'ICICI Lombard General Insurance', basePrice: 1685.60, sector: 'Insurance' },
    { symbol: 'ICICIPRULI', name: 'ICICI Prudential Life', basePrice: 585.40, sector: 'Insurance' },
    { symbol: 'HDFCAMC', name: 'HDFC Asset Management', basePrice: 3250.75, sector: 'Finance' },

    // IT & Technology
    { symbol: 'PERSISTENT', name: 'Persistent Systems', basePrice: 5450.80, sector: 'IT' },
    { symbol: 'COFORGE', name: 'Coforge Limited', basePrice: 4850.30, sector: 'IT' },
    { symbol: 'MPHASIS', name: 'Mphasis Limited', basePrice: 2650.60, sector: 'IT' },
    { symbol: 'LTTS', name: 'L&T Technology Services', basePrice: 4950.40, sector: 'IT' },
    { symbol: 'TATAELXSI', name: 'Tata Elxsi', basePrice: 7250.75, sector: 'IT' },
    { symbol: 'OFSS', name: 'Oracle Financial Services', basePrice: 11250.80, sector: 'IT' },
    { symbol: 'SONACOMS', name: 'Sona BLW Precision', basePrice: 585.30, sector: 'Auto Components' },
    { symbol: 'ROUTE', name: 'Route Mobile', basePrice: 1685.60, sector: 'IT' },

    // Pharma & Healthcare
    { symbol: 'AUROPHARMA', name: 'Aurobindo Pharma', basePrice: 1185.40, sector: 'Pharma' },
    { symbol: 'LUPIN', name: 'Lupin Limited', basePrice: 1685.75, sector: 'Pharma' },
    { symbol: 'BIOCON', name: 'Biocon Limited', basePrice: 325.60, sector: 'Pharma' },
    { symbol: 'TORNTPHARM', name: 'Torrent Pharmaceuticals', basePrice: 2850.80, sector: 'Pharma' },
    { symbol: 'ALKEM', name: 'Alkem Laboratories', basePrice: 5450.30, sector: 'Pharma' },
    { symbol: 'ABBOTINDIA', name: 'Abbott India', basePrice: 27500.60, sector: 'Pharma' },
    { symbol: 'GLENMARK', name: 'Glenmark Pharmaceuticals', basePrice: 1485.40, sector: 'Pharma' },
    { symbol: 'IPCALAB', name: 'IPCA Laboratories', basePrice: 1285.75, sector: 'Pharma' },
    { symbol: 'LAURUSLABS', name: 'Laurus Labs', basePrice: 485.60, sector: 'Pharma' },
    { symbol: 'GRANULES', name: 'Granules India', basePrice: 485.80, sector: 'Pharma' },
    { symbol: 'MAXHEALTH', name: 'Max Healthcare', basePrice: 885.30, sector: 'Healthcare' },
    { symbol: 'FORTIS', name: 'Fortis Healthcare', basePrice: 425.60, sector: 'Healthcare' },
    { symbol: 'METROPOLIS', name: 'Metropolis Healthcare', basePrice: 1685.40, sector: 'Healthcare' },

    // Auto & Auto Components
    { symbol: 'TVSMOTOR', name: 'TVS Motor Company', basePrice: 2450.75, sector: 'Auto' },
    { symbol: 'ASHOKLEY', name: 'Ashok Leyland', basePrice: 185.60, sector: 'Auto' },
    { symbol: 'ESCORTS', name: 'Escorts Kubota', basePrice: 3450.80, sector: 'Auto' },
    { symbol: 'MOTHERSON', name: 'Samvardhana Motherson', basePrice: 125.30, sector: 'Auto Components' },
    { symbol: 'BOSCHLTD', name: 'Bosch Limited', basePrice: 32500.60, sector: 'Auto Components' },
    { symbol: 'EXIDEIND', name: 'Exide Industries', basePrice: 425.40, sector: 'Auto Components' },
    { symbol: 'AMARAJABAT', name: 'Amara Raja Energy', basePrice: 685.75, sector: 'Auto Components' },
    { symbol: 'MRF', name: 'MRF Limited', basePrice: 125000.80, sector: 'Auto Components' },
    { symbol: 'APOLLOTYRE', name: 'Apollo Tyres', basePrice: 485.30, sector: 'Auto Components' },
    { symbol: 'CEAT', name: 'CEAT Limited', basePrice: 2650.60, sector: 'Auto Components' },
    { symbol: 'BALKRISIND', name: 'Balkrishna Industries', basePrice: 2850.40, sector: 'Auto Components' },

    // FMCG & Consumer
    { symbol: 'DABUR', name: 'Dabur India', basePrice: 585.75, sector: 'FMCG' },
    { symbol: 'MARICO', name: 'Marico Limited', basePrice: 585.60, sector: 'FMCG' },
    { symbol: 'GODREJCP', name: 'Godrej Consumer Products', basePrice: 1185.40, sector: 'FMCG' },
    { symbol: 'COLPAL', name: 'Colgate-Palmolive India', basePrice: 2850.80, sector: 'FMCG' },
    { symbol: 'PGHH', name: 'Procter & Gamble Hygiene', basePrice: 15500.30, sector: 'FMCG' },
    { symbol: 'EMAMILTD', name: 'Emami Limited', basePrice: 585.60, sector: 'FMCG' },
    { symbol: 'GILLETTE', name: 'Gillette India', basePrice: 6850.40, sector: 'FMCG' },
    { symbol: 'VBL', name: 'Varun Beverages', basePrice: 1485.75, sector: 'FMCG' },
    { symbol: 'TATAPOWER', name: 'Tata Power', basePrice: 385.60, sector: 'Power' },
    { symbol: 'JUBLFOOD', name: 'Jubilant Foodworks', basePrice: 585.80, sector: 'Consumer' },
    { symbol: 'WESTLIFE', name: 'Westlife Foodworld', basePrice: 885.30, sector: 'Consumer' },
    { symbol: 'ZOMATO', name: 'Zomato Limited', basePrice: 185.60, sector: 'Consumer' },
    { symbol: 'NYKAA', name: 'FSN E-Commerce (Nykaa)', basePrice: 185.40, sector: 'Consumer' },

    // Metals & Mining
    { symbol: 'VEDL', name: 'Vedanta Limited', basePrice: 385.75, sector: 'Metals' },
    { symbol: 'NMDC', name: 'NMDC Limited', basePrice: 225.60, sector: 'Mining' },
    { symbol: 'SAIL', name: 'Steel Authority of India', basePrice: 115.40, sector: 'Steel' },
    { symbol: 'JINDALSTEL', name: 'Jindal Steel & Power', basePrice: 885.80, sector: 'Steel' },
    { symbol: 'NATIONALUM', name: 'National Aluminium', basePrice: 185.30, sector: 'Metals' },
    { symbol: 'MOIL', name: 'MOIL Limited', basePrice: 385.60, sector: 'Mining' },
    { symbol: 'RATNAMANI', name: 'Ratnamani Metals', basePrice: 2850.40, sector: 'Metals' },

    // Cement
    { symbol: 'AMBUJACEM', name: 'Ambuja Cements', basePrice: 585.75, sector: 'Cement' },
    { symbol: 'ACC', name: 'ACC Limited', basePrice: 2450.60, sector: 'Cement' },
    { symbol: 'SHREECEM', name: 'Shree Cement', basePrice: 27500.80, sector: 'Cement' },
    { symbol: 'DALMIACEM', name: 'Dalmia Bharat', basePrice: 2150.30, sector: 'Cement' },
    { symbol: 'JKCEMENT', name: 'JK Cement', basePrice: 3850.60, sector: 'Cement' },
    { symbol: 'RAMCOCEM', name: 'Ramco Cements', basePrice: 985.40, sector: 'Cement' },

    // Infrastructure & Construction
    { symbol: 'DLF', name: 'DLF Limited', basePrice: 785.75, sector: 'Real Estate' },
    { symbol: 'OBEROIRLTY', name: 'Oberoi Realty', basePrice: 1685.60, sector: 'Real Estate' },
    { symbol: 'GODREJPROP', name: 'Godrej Properties', basePrice: 2450.40, sector: 'Real Estate' },
    { symbol: 'PRESTIGE', name: 'Prestige Estates', basePrice: 1685.80, sector: 'Real Estate' },
    { symbol: 'BRIGADE', name: 'Brigade Enterprises', basePrice: 985.30, sector: 'Real Estate' },
    { symbol: 'IPCL', name: 'India Cements', basePrice: 285.60, sector: 'Cement' },
    { symbol: 'NBCC', name: 'NBCC India', basePrice: 85.40, sector: 'Construction' },
    { symbol: 'IRCON', name: 'Ircon International', basePrice: 185.75, sector: 'Construction' },
    { symbol: 'RVNL', name: 'Rail Vikas Nigam', basePrice: 385.60, sector: 'Construction' },

    // Telecom & Media
    { symbol: 'INDIGO', name: 'InterGlobe Aviation', basePrice: 3850.80, sector: 'Aviation' },
    { symbol: 'ZEEL', name: 'Zee Entertainment', basePrice: 185.30, sector: 'Media' },
    { symbol: 'SUNTV', name: 'Sun TV Network', basePrice: 685.60, sector: 'Media' },
    { symbol: 'PVRINOX', name: 'PVR INOX', basePrice: 1485.40, sector: 'Entertainment' },
    { symbol: 'NETWORK18', name: 'Network18 Media', basePrice: 85.75, sector: 'Media' },

    // Energy & Power
    { symbol: 'ADANIGREEN', name: 'Adani Green Energy', basePrice: 1685.60, sector: 'Power' },
    { symbol: 'ADANIPOWER', name: 'Adani Power', basePrice: 485.40, sector: 'Power' },
    { symbol: 'TORNTPOWER', name: 'Torrent Power', basePrice: 1285.75, sector: 'Power' },
    { symbol: 'NHPC', name: 'NHPC Limited', basePrice: 85.60, sector: 'Power' },
    { symbol: 'SJVN', name: 'SJVN Limited', basePrice: 105.40, sector: 'Power' },
    { symbol: 'IOC', name: 'Indian Oil Corporation', basePrice: 125.80, sector: 'Energy' },
    { symbol: 'HINDPETRO', name: 'Hindustan Petroleum', basePrice: 385.30, sector: 'Energy' },
    { symbol: 'GAIL', name: 'GAIL India', basePrice: 185.60, sector: 'Energy' },
    { symbol: 'OIL', name: 'Oil India', basePrice: 385.40, sector: 'Energy' },

    // Chemicals & Fertilizers
    { symbol: 'UPL', name: 'UPL Limited', basePrice: 585.75, sector: 'Chemicals' },
    { symbol: 'PIDILITIND', name: 'Pidilite Industries', basePrice: 2850.60, sector: 'Chemicals' },
    { symbol: 'AARTI', name: 'Aarti Industries', basePrice: 685.40, sector: 'Chemicals' },
    { symbol: 'DEEPAKNTR', name: 'Deepak Nitrite', basePrice: 2150.80, sector: 'Chemicals' },
    { symbol: 'SRF', name: 'SRF Limited', basePrice: 2450.30, sector: 'Chemicals' },
    { symbol: 'BALRAMCHIN', name: 'Balrampur Chini Mills', basePrice: 485.60, sector: 'Sugar' },
    { symbol: 'CHAMBLFERT', name: 'Chambal Fertilizers', basePrice: 485.40, sector: 'Fertilizers' },
    { symbol: 'COROMANDEL', name: 'Coromandel International', basePrice: 1685.75, sector: 'Fertilizers' },

    // Textiles & Apparel
    { symbol: 'APLAPOLLO', name: 'APL Apollo Tubes', basePrice: 1485.60, sector: 'Steel Products' },
    { symbol: 'RAYMOND', name: 'Raymond Limited', basePrice: 1685.40, sector: 'Textiles' },
    { symbol: 'GOKEX', name: 'Gopal Snacks', basePrice: 485.80, sector: 'FMCG' },
    { symbol: 'PAGEIND', name: 'Page Industries', basePrice: 42500.30, sector: 'Apparel' },
    { symbol: 'TRENT', name: 'Trent Limited', basePrice: 4850.60, sector: 'Retail' },
    { symbol: 'ABFRL', name: 'Aditya Birla Fashion', basePrice: 285.40, sector: 'Retail' },

    // Diversified & Others
    { symbol: 'SIEMENS', name: 'Siemens Limited', basePrice: 5850.75, sector: 'Engineering' },
    { symbol: 'ABB', name: 'ABB India', basePrice: 6850.60, sector: 'Engineering' },
    { symbol: 'HAVELLS', name: 'Havells India', basePrice: 1685.40, sector: 'Electricals' },
    { symbol: 'VOLTAS', name: 'Voltas Limited', basePrice: 1285.80, sector: 'Consumer Durables' },
    { symbol: 'WHIRLPOOL', name: 'Whirlpool of India', basePrice: 1685.30, sector: 'Consumer Durables' },
    { symbol: 'CROMPTON', name: 'Crompton Greaves Consumer', basePrice: 385.60, sector: 'Electricals' },
    { symbol: 'POLYCAB', name: 'Polycab India', basePrice: 5850.40, sector: 'Cables' },
    { symbol: 'KEI', name: 'KEI Industries', basePrice: 3850.75, sector: 'Cables' },
    { symbol: 'DIXON', name: 'Dixon Technologies', basePrice: 12500.60, sector: 'Electronics' },
    { symbol: 'AMBER', name: 'Amber Enterprises', basePrice: 4850.80, sector: 'Consumer Durables' },
    { symbol: 'BLUESTAR', name: 'Blue Star', basePrice: 1685.30, sector: 'Consumer Durables' },
    { symbol: 'CUMMINSIND', name: 'Cummins India', basePrice: 3250.60, sector: 'Engineering' },
    { symbol: 'THERMAX', name: 'Thermax Limited', basePrice: 4250.40, sector: 'Engineering' },
    { symbol: 'SCHAEFFLER', name: 'Schaeffler India', basePrice: 3850.75, sector: 'Auto Components' },
    { symbol: 'TIMKEN', name: 'Timken India', basePrice: 3450.60, sector: 'Engineering' },
    { symbol: 'GRINDWELL', name: 'Grindwell Norton', basePrice: 2850.80, sector: 'Abrasives' },
    { symbol: 'CARBORUNIV', name: 'Carborundum Universal', basePrice: 1285.30, sector: 'Abrasives' },

    // Additional Mid & Small Cap Stocks
    { symbol: 'IRCTC', name: 'Indian Railway Catering', basePrice: 785.60, sector: 'Tourism' },
    { symbol: 'IRFC', name: 'Indian Railway Finance', basePrice: 145.40, sector: 'Finance' },
    { symbol: 'CONCOR', name: 'Container Corporation', basePrice: 785.75, sector: 'Logistics' },
    { symbol: 'GICRE', name: 'General Insurance Corp', basePrice: 385.60, sector: 'Insurance' },
    { symbol: 'NIACL', name: 'New India Assurance', basePrice: 185.40, sector: 'Insurance' },
    { symbol: 'STARHEALTH', name: 'Star Health Insurance', basePrice: 585.80, sector: 'Insurance' },
    { symbol: 'POLICYBZR', name: 'PB Fintech (Policybazaar)', basePrice: 1285.30, sector: 'Fintech' },
    { symbol: 'PAYTM', name: 'One97 Communications (Paytm)', basePrice: 685.60, sector: 'Fintech' },
    { symbol: 'DMART', name: 'Avenue Supermarts (DMart)', basePrice: 3850.40, sector: 'Retail' },
    { symbol: 'RELAXO', name: 'Relaxo Footwears', basePrice: 985.75, sector: 'Footwear' },
    { symbol: 'BATA', name: 'Bata India', basePrice: 1485.60, sector: 'Footwear' },
    { symbol: 'VGUARD', name: 'V-Guard Industries', basePrice: 385.40, sector: 'Electricals' },
    { symbol: 'SYMPHONY', name: 'Symphony Limited', basePrice: 1285.80, sector: 'Consumer Durables' },
    { symbol: 'RAJESHEXPO', name: 'Rajesh Exports', basePrice: 285.30, sector: 'Jewelry' },
    { symbol: 'KALYANKJIL', name: 'Kalyan Jewellers', basePrice: 485.60, sector: 'Jewelry' },
    { symbol: 'PCJEWELLER', name: 'PC Jeweller', basePrice: 25.40, sector: 'Jewelry' },
    { symbol: 'JUBLPHARMA', name: 'Jubilant Pharmova', basePrice: 985.75, sector: 'Pharma' },
    { symbol: 'SYNGENE', name: 'Syngene International', basePrice: 785.60, sector: 'Pharma' },
    { symbol: 'LALPATHLAB', name: 'Dr. Lal PathLabs', basePrice: 2850.40, sector: 'Healthcare' },
    { symbol: 'THYROCARE', name: 'Thyrocare Technologies', basePrice: 685.80, sector: 'Healthcare' },
    { symbol: 'KPITTECH', name: 'KPIT Technologies', basePrice: 1485.30, sector: 'IT' },
    { symbol: 'CYIENT', name: 'Cyient Limited', basePrice: 1685.60, sector: 'IT' },
    { symbol: 'MASTEK', name: 'Mastek Limited', basePrice: 2850.40, sector: 'IT' },
    { symbol: 'INTELLECT', name: 'Intellect Design Arena', basePrice: 785.75, sector: 'IT' },
    { symbol: 'HAPPSTMNDS', name: 'Happiest Minds Tech', basePrice: 885.60, sector: 'IT' },
    { symbol: 'ZENSARTECH', name: 'Zensar Technologies', basePrice: 585.40, sector: 'IT' },
    { symbol: 'MINDACORP', name: 'Minda Corporation', basePrice: 485.80, sector: 'Auto Components' },
    { symbol: 'ENDURANCE', name: 'Endurance Technologies', basePrice: 1685.30, sector: 'Auto Components' },
    { symbol: 'SUPRAJIT', name: 'Suprajit Engineering', basePrice: 485.60, sector: 'Auto Components' },
    { symbol: 'FINCABLES', name: 'Finolex Cables', basePrice: 985.40, sector: 'Cables' },
    { symbol: 'ATUL', name: 'Atul Limited', basePrice: 7250.75, sector: 'Chemicals' },
    { symbol: 'NAVINFLUOR', name: 'Navin Fluorine', basePrice: 4850.60, sector: 'Chemicals' },
    { symbol: 'CLEAN', name: 'Clean Science', basePrice: 1685.80, sector: 'Chemicals' },
    { symbol: 'TATACHEM', name: 'Tata Chemicals', basePrice: 1085.30, sector: 'Chemicals' },
    { symbol: 'GNFC', name: 'Gujarat Narmada Fertilizers', basePrice: 685.60, sector: 'Fertilizers' },
    { symbol: 'GSFC', name: 'Gujarat State Fertilizers', basePrice: 185.40, sector: 'Fertilizers' },
    { symbol: 'FACT', name: 'Fertilizers and Chemicals', basePrice: 685.75, sector: 'Fertilizers' },
    { symbol: 'NFL', name: 'National Fertilizers', basePrice: 85.60, sector: 'Fertilizers' },
    { symbol: 'KANSAINER', name: 'Kansai Nerolac Paints', basePrice: 385.40, sector: 'Paints' },
    { symbol: 'AKZOINDIA', name: 'Akzo Nobel India', basePrice: 2850.80, sector: 'Paints' },
    { symbol: 'BERGEPAINT', name: 'Berger Paints', basePrice: 585.30, sector: 'Paints' },
    { symbol: 'INDIAMART', name: 'IndiaMART InterMESH', basePrice: 2850.60, sector: 'Internet' },
    { symbol: 'JUSTDIAL', name: 'Just Dial', basePrice: 985.40, sector: 'Internet' },
    { symbol: 'NAUKRI', name: 'Info Edge (Naukri)', basePrice: 5850.75, sector: 'Internet' },
    { symbol: 'ZOMATO', name: 'Zomato Limited', basePrice: 185.60, sector: 'Food Delivery' },
    { symbol: 'SWIGGY', name: 'Swiggy Limited', basePrice: 485.40, sector: 'Food Delivery' },
    { symbol: 'BLINKIT', name: 'Blinkit (Grofers)', basePrice: 285.80, sector: 'Quick Commerce' },
    { symbol: 'BIKAJI', name: 'Bikaji Foods', basePrice: 585.30, sector: 'FMCG' },
    { symbol: 'MRPL', name: 'Mangalore Refinery', basePrice: 185.60, sector: 'Energy' },
    { symbol: 'GSPL', name: 'Gujarat State Petronet', basePrice: 385.40, sector: 'Energy' },
    { symbol: 'PETRONET', name: 'Petronet LNG', basePrice: 325.75, sector: 'Energy' },
    { symbol: 'IGL', name: 'Indraprastha Gas', basePrice: 485.60, sector: 'Energy' },
    { symbol: 'MGL', name: 'Mahanagar Gas', basePrice: 1285.40, sector: 'Energy' },
    { symbol: 'GUJGASLTD', name: 'Gujarat Gas', basePrice: 585.80, sector: 'Energy' },
    { symbol: 'AEGISLOG', name: 'Aegis Logistics', basePrice: 385.30, sector: 'Logistics' },
    { symbol: 'BLUEDART', name: 'Blue Dart Express', basePrice: 7850.60, sector: 'Logistics' },
    { symbol: 'DELHIVERY', name: 'Delhivery Limited', basePrice: 385.40, sector: 'Logistics' },
    { symbol: 'VRL', name: 'VRL Logistics', basePrice: 585.75, sector: 'Logistics' },
    { symbol: 'MAHLOG', name: 'Mahindra Logistics', basePrice: 485.60, sector: 'Logistics' },
    { symbol: 'TIINDIA', name: 'Tube Investments of India', basePrice: 3850.40, sector: 'Engineering' },
    { symbol: 'CRISIL', name: 'CRISIL Limited', basePrice: 4850.80, sector: 'Financial Services' },
    { symbol: 'CDSL', name: 'Central Depository Services', basePrice: 1685.30, sector: 'Financial Services' },
    { symbol: 'MAZDOCK', name: 'Mazagon Dock Shipbuilders', basePrice: 2850.60, sector: 'Defense' },
    { symbol: 'HAL', name: 'Hindustan Aeronautics', basePrice: 4250.75, sector: 'Defense' },
    { symbol: 'BEL', name: 'Bharat Electronics', basePrice: 285.40, sector: 'Defense' },
    { symbol: 'COCHINSHIP', name: 'Cochin Shipyard', basePrice: 1685.60, sector: 'Defense' },
    { symbol: 'GRSE', name: 'Garden Reach Shipbuilders', basePrice: 1285.80, sector: 'Defense' },
    { symbol: 'BEML', name: 'BEML Limited', basePrice: 2850.30, sector: 'Defense' },
    { symbol: 'SOLARINDS', name: 'Solar Industries', basePrice: 7850.60, sector: 'Chemicals' },
    { symbol: 'EIDPARRY', name: 'EID Parry India', basePrice: 685.40, sector: 'Sugar' },
    { symbol: 'DHAMPUR', name: 'Dhampur Sugar Mills', basePrice: 385.75, sector: 'Sugar' },
    { symbol: 'TRIVENI', name: 'Triveni Engineering', basePrice: 485.60, sector: 'Sugar' },
    { symbol: 'RENUKA', name: 'Shree Renuka Sugars', basePrice: 45.80, sector: 'Sugar' },
    { symbol: 'BAJAJHLDNG', name: 'Bajaj Holdings', basePrice: 8850.30, sector: 'Finance' },
    { symbol: 'PRAJIND', name: 'Praj Industries', basePrice: 585.60, sector: 'Engineering' },
    { symbol: 'KALPATPOWR', name: 'Kalpataru Projects', basePrice: 1285.40, sector: 'Construction' },
    { symbol: 'KEC', name: 'KEC International', basePrice: 685.75, sector: 'Construction' },
    { symbol: 'JKPAPER', name: 'JK Paper', basePrice: 485.60, sector: 'Paper' },
    { symbol: 'TNPL', name: 'Tamil Nadu Newsprint', basePrice: 485.40, sector: 'Paper' },
    { symbol: 'WSTCSTPAPR', name: 'West Coast Paper Mills', basePrice: 485.80, sector: 'Paper' },
    { symbol: 'CENTURYPLY', name: 'Century Plyboards', basePrice: 785.30, sector: 'Building Materials' },
    { symbol: 'GREENPLY', name: 'Greenply Industries', basePrice: 285.60, sector: 'Building Materials' },
    { symbol: 'ASTRAL', name: 'Astral Limited', basePrice: 1685.40, sector: 'Building Materials' },
    { symbol: 'SUPREMEIND', name: 'Supreme Industries', basePrice: 4850.75, sector: 'Plastics' },
    { symbol: 'NILKAMAL', name: 'Nilkamal Limited', basePrice: 2450.60, sector: 'Plastics' },
    { symbol: 'SINTEX', name: 'Sintex Industries', basePrice: 15.80, sector: 'Plastics' },
    { symbol: 'JYOTHYLAB', name: 'Jyothy Labs', basePrice: 485.30, sector: 'FMCG' },
    { symbol: 'HONAUT', name: 'Honeywell Automation', basePrice: 42500.60, sector: 'Engineering' },
    { symbol: 'SKFINDIA', name: 'SKF India', basePrice: 5850.40, sector: 'Engineering' },
    { symbol: 'FOSECOIND', name: 'Foseco India', basePrice: 4850.75, sector: 'Chemicals' },
    { symbol: 'SWANENERGY', name: 'Swan Energy', basePrice: 585.60, sector: 'Textiles' },
    { symbol: 'WELCORP', name: 'Welspun Corp', basePrice: 585.40, sector: 'Steel Products' },
    { symbol: 'WELSPUNIND', name: 'Welspun India', basePrice: 185.80, sector: 'Textiles' },
    { symbol: 'TRIDENT', name: 'Trident Limited', basePrice: 45.30, sector: 'Textiles' },
    { symbol: 'VARDHACRLC', name: 'Vardhman Textiles', basePrice: 485.60, sector: 'Textiles' },
    { symbol: 'ALOKTEXT', name: 'Alok Industries', basePrice: 25.40, sector: 'Textiles' },
    { symbol: 'SPTL', name: 'Sintex Plastics', basePrice: 15.75, sector: 'Plastics' },
    { symbol: 'JKLAKSHMI', name: 'JK Lakshmi Cement', basePrice: 785.60, sector: 'Cement' },
    { symbol: 'ORIENTCEM', name: 'Orient Cement', basePrice: 185.40, sector: 'Cement' },
    { symbol: 'STARCEMENT', name: 'Star Cement', basePrice: 185.80, sector: 'Cement' },
    { symbol: 'HEIDELBERG', name: 'HeidelbergCement India', basePrice: 285.30, sector: 'Cement' },
    { symbol: 'PRSMJOHNSN', name: 'Prism Johnson', basePrice: 185.60, sector: 'Cement' },
    { symbol: 'JSWENERGY', name: 'JSW Energy', basePrice: 585.40, sector: 'Power' },
    { symbol: 'CESC', name: 'CESC Limited', basePrice: 185.75, sector: 'Power' },
    { symbol: 'RPOWER', name: 'Reliance Power', basePrice: 25.60, sector: 'Power' },
    { symbol: 'JPPOWER', name: 'Jaiprakash Power', basePrice: 15.40, sector: 'Power' },
    { symbol: 'SUZLON', name: 'Suzlon Energy', basePrice: 45.80, sector: 'Power' },
    { symbol: 'INOXWIND', name: 'Inox Wind', basePrice: 185.30, sector: 'Power' },
    { symbol: 'ORIENTELEC', name: 'Orient Electric', basePrice: 285.60, sector: 'Electricals' },
    { symbol: 'BAJAJHIND', name: 'Bajaj Hindusthan Sugar', basePrice: 35.40, sector: 'Sugar' },
    { symbol: 'MAITHANALL', name: 'Maithan Alloys', basePrice: 1285.75, sector: 'Metals' },
    { symbol: 'GRAPHITE', name: 'Graphite India', basePrice: 585.60, sector: 'Metals' },
    { symbol: 'HEG', name: 'HEG Limited', basePrice: 1685.40, sector: 'Metals' },
    { symbol: 'ELECTCAST', name: 'Electrosteel Castings', basePrice: 185.80, sector: 'Steel' },
    { symbol: 'APARINDS', name: 'Apar Industries', basePrice: 7850.30, sector: 'Cables' },
    { symbol: 'UNIVCABLES', name: 'Universal Cables', basePrice: 385.60, sector: 'Cables' },
    { symbol: 'FILATEX', name: 'Filatex India', basePrice: 185.40, sector: 'Textiles' },
    { symbol: 'GUJALKALI', name: 'Gujarat Alkalies', basePrice: 785.75, sector: 'Chemicals' },
    { symbol: 'DCMSHRIRAM', name: 'DCM Shriram', basePrice: 985.60, sector: 'Chemicals' },
    { symbol: 'NOCIL', name: 'NOCIL Limited', basePrice: 285.40, sector: 'Chemicals' },
    { symbol: 'ALKYLAMINE', name: 'Alkyl Amines Chemicals', basePrice: 2850.80, sector: 'Chemicals' },
    { symbol: 'FINEORG', name: 'Fine Organic Industries', basePrice: 5850.30, sector: 'Chemicals' },
    { symbol: 'ROSSARI', name: 'Rossari Biotech', basePrice: 985.60, sector: 'Chemicals' },
    { symbol: 'ANANTRAJ', name: 'Anant Raj', basePrice: 485.40, sector: 'Real Estate' },
    { symbol: 'PHOENIXLTD', name: 'Phoenix Mills', basePrice: 1685.75, sector: 'Real Estate' },
    { symbol: 'MAHLIFE', name: 'Mahindra Lifespace', basePrice: 485.60, sector: 'Real Estate' },
    { symbol: 'SOBHA', name: 'Sobha Limited', basePrice: 1285.40, sector: 'Real Estate' },
    { symbol: 'KOLTEPATIL', name: 'Kolte-Patil Developers', basePrice: 385.80, sector: 'Real Estate' },
    { symbol: 'SUNTECK', name: 'Sunteck Realty', basePrice: 485.30, sector: 'Real Estate' },
    { symbol: 'MAHINDCIE', name: 'Mahindra CIE Automotive', basePrice: 385.60, sector: 'Auto Components' },
    { symbol: 'JTEKTINDIA', name: 'JTEKT India', basePrice: 185.40, sector: 'Auto Components' },
    { symbol: 'WABCOINDIA', name: 'Wabco India', basePrice: 8850.75, sector: 'Auto Components' },
    { symbol: 'GABRIEL', name: 'Gabriel India', basePrice: 385.60, sector: 'Auto Components' },
    { symbol: 'FMGOETZE', name: 'Federal-Mogul Goetze', basePrice: 485.40, sector: 'Auto Components' },
    { symbol: 'WHEELS', name: 'Wheels India', basePrice: 985.80, sector: 'Auto Components' },
    { symbol: 'SWARAJENG', name: 'Swaraj Engines', basePrice: 2850.30, sector: 'Auto Components' },
    { symbol: 'MAHSCOOTER', name: 'Maharashtra Scooters', basePrice: 7850.60, sector: 'Auto' },
    { symbol: 'FORCEMOT', name: 'Force Motors', basePrice: 4850.40, sector: 'Auto' },
    { symbol: 'SML', name: 'SML Isuzu', basePrice: 1685.75, sector: 'Auto' },
    { symbol: 'TITAGARH', name: 'Titagarh Rail Systems', basePrice: 985.60, sector: 'Engineering' },
    { symbol: 'TEXRAIL', name: 'Texmaco Rail', basePrice: 185.40, sector: 'Engineering' },
    { symbol: 'ELECON', name: 'Elecon Engineering', basePrice: 485.80, sector: 'Engineering' },
    { symbol: 'TRIVENI', name: 'Triveni Turbine', basePrice: 585.30, sector: 'Engineering' },
    { symbol: 'KIRLOSENG', name: 'Kirloskar Oil Engines', basePrice: 1285.60, sector: 'Engineering' },
    { symbol: 'KIRLOSBROS', name: 'Kirloskar Brothers', basePrice: 1685.40, sector: 'Engineering' },
    { symbol: 'KIRLFER', name: 'Kirloskar Ferrous', basePrice: 485.75, sector: 'Steel' },
    { symbol: 'KIRLPNU', name: 'Kirloskar Pneumatic', basePrice: 985.60, sector: 'Engineering' },
    { symbol: 'WABAG', name: 'VA Tech Wabag', basePrice: 985.40, sector: 'Engineering' },
    { symbol: 'AIAENG', name: 'AIA Engineering', basePrice: 3850.80, sector: 'Engineering' },
    { symbol: 'TIIL', name: 'Technocraft Industries', basePrice: 485.30, sector: 'Engineering' },
];

// Export for use in main app
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { nseStocksData };
}